# run-custompios action.yml
# written by Stephan Wendel aka KwadFan <me@stephanwe.de>
# Copyright 2022
# This file is distributed under GPLv3
name: run-custompios
description: Run CustomPiOS as git action
author: Stephan Wendel aka KwadFan
branding: box
color: red

inputs:
  # CustomPiOS checkout setup
  custompios_repo:
    description: "Use specific CustomPiOS repository"
    required: true
    default: "guysoft/CustomPiOS"

  custompios_branch:
    description: "Use specific CustomPiOS branch"
    required: false
    default: ""

  custompios_commit:
    description: "Use specific CustomPiOS branch"
    required: false
    default: ""

  # CustomPiOS build setup
  modules:
    description: "Path to modules (usually src/)"
    required: true

  image:
    description: "Path to modules (usually src/image)"
    required: false

  workspace:
    description: "Path to workspace (usually src/workspace)"
    required: false

  # For Development only!
  debug:
    description: "Verbose output for Debugging only!"
    required: false
    default: "false"

  testaction:
    description: "Verbose output for Debugging only!"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    # required not working as expected
    # see https://github.com/actions/runner/issues/1070

    - name: "Check Inputs"
      shell: bash
      run: |
        if [[ -n "${{ inputs.modules }}" ]]; then
          echo -e "\e[31mPath to modules not set! Exiting...\e[0m"
          exit 1
        fi

    - name: "Enable loop module"
      shell: bash
      run: |
        sudo modprobe loop

    - name: "Build Container"
      shell: bash
      run: |
        docker build --tag kwadfan:run-custompios \
        https://github.com/KwadFan/run-custompios.git#main:src

    - name: "Run CustomPiOS"
      shell: bash
      run: |

        # Docker default parameters
        DOCKER_PARAM=(--rm --privileged)

        if [[ "${{ inputs.testaction }}" = "true" ]]; then
          DOCKER_PARAM+=(--env ACTION_DEBUG=true)
          DOCKER_PARAM+=(--env CUSTOMPIOS_REPO=${{ inputs.custompios_repo }})
        fi

        docker run "${DOCKER_PARAM[@]}" kwadfan:run-custompios
