# run-custompios action.yml
# written by Stephan Wendel aka KwadFan <me@stephanwe.de>
# Copyright 2022
# This file is distributed under GPLv3
name: run-custompios
description: Run CustomPiOS as git action
author: Stephan Wendel aka KwadFan
branding: box
color: red

inputs:
  custompios_repo:
    description: "Use specific CustomPiOS repository"
    required: true
    default: "guysoft/CustomPiOS"

  custompios_branch:
    description: "Use specific CustomPiOS branch"
    required: false
    default: ""

  custompios_commit:
    description: "Use specific CustomPiOS branch"
    required: false
    default: ""

  workspace:
    description: Path to 'src' directory
    required: true

  # For Development only!
  debug:
    description: "Verbose output for Debugging only!"
    required: false
    default: "false"

  testaction:
    description: "Verbose output for Debugging only!"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: "Enable loop module"
      shell: bash
      run: |
        sudo modprobe loop

    - name: "Build Container"
      shell: bash
      run: |
        docker build --tag kwadfan:run-custompios \
        https://github.com/KwadFan/run-custompios.git#main:src

    - name: "Run CustomPiOS"
      shell: bash
      run: |

        if [[ "${{ inputs.testaction }}" = ]]; then
          docker run --env-file ./test/testenv kwadfan:run-custompios
        fi
