name: Tests

on:
  push:

  workflow_dispatch:

jobs:
  printenv:
    runs-on: ubuntu-latest

    steps:
      - name: Print Env
        run: |
          echo $GITHUB_ENV
          echo $GITHUB_EVENT_PATH

      - name:
        id: build-image
        uses: KwadFan/run-custompios
