name: Tests

on:
  push:

  workflow_dispatch:

jobs:
  printenv:
    runs-on: ubuntu-latest

    steps:
      - name: Run CustomPiOS
        id: build-image
        uses: KwadFan/run-custompios@main
