name: Tests

on:
  push:

  workflow_dispatch:

jobs:
  testaction:
    runs-on: ubuntu-latest

    steps:
      - name: Run CustomPiOS
        uses: KwadFan/run-custompios@main
        with:
          modules: src
          testaction: true
